#' Retrieve stream distance matrices by network in numeric order
#' 
#'@description
#'
#'This function retrieves the distance matrices that have been created for a SpatialStreamNetwork and orders them by network name. 
#'
#'@usage
#'
#'\code{getStreamDistMatInOrder.predsxobs(x)}
#'
#'@param x An object of class SpatialStreamNetwork. The folder where the data for the SpatialStreamNetwork are stored must contain the distance matrix files generated by \code{createDistMat} from the package SSN.
#'@return A list of the distance matrices for the SpatialStreamNetwork, ordered numerically by the network ID.
#'
#'@details
#'
#'This function addresses the problem that the function \code{getStreamDistMat} returns a list of distance matrices but not in order of network ID. It orders the network IDs in alphanumeric order, meaning that, if a SpatialStreamNetwork has 10 networks, the order will appear as 1, 10, 2, 3, 4, ..., etc.This function differs from \code{\link{getStreamDistMatsInOrder}} in that this function returns only the distance matrices between observed and predicted sites. The other function returns only the distance matrices among the observed and prediction sites, separately. 
#'
#'@export
getStreamDistMatInOrder.predsxobs <- function(x){
  
  # Get stream distance matrices
  
  unordered.distmats <- getStreamDistMat(x, "preds")
  
  # If for preds, identify A, B matrices and remove
  
  ind <- identifyObsxPredsABMatrices(unordered.distmats)
    
  unordered.distmats <- unordered.distmats[ind]
    
  # Names are in alphabetical order
  
  unordered.names <- names(unordered.distmats)
  
  # Strip away the parts of the names that include dist.net
  
  unordered.names <- gsub("dist.net", "", unordered.names)
  
  # Strip away the parts that include .a and .b
  
  unordered.names <- gsub(".[ab]{1}", "", unordered.names)
  
  # Convert to numbers
  
  unordered.names <- as.numeric(unordered.names)
  
  # Find correct sorting order
  
  sort.order <- order(unordered.names)
  
  # Sort list
  
  ordered.distmats <- unordered.distmats[sort.order]
  
  # Return result
  
  return(ordered.distmats)
  
}
