#' Identify what elements in a list of distance matrices are for distances between observed and predicted sites.
#' 
#'@description 
#'
#'This function identifies elements in a list of distance matrices which report distances between observed and predicted sites.
#'   
#'@usage 
#' 
#'\code{identifyObsxPredsABMatrices(dist.matrices)}
#' 
#'@param dist.matrices A list of distance matrices generated by calling \code{\link{getStreamDistMatsInOrder}} for the prediction sites in a SpatialStreamNetwork.
#'@return A logical vector indicating the positions of the distance matrices between observed and predicted sites.
#'
#'@details
#'
#'This function is called internally inside both \code{\link{getStreamDistMatsInOrder}} and \code{\link{getStreamDistMatsInOrder.predsxobs}}. It is used to identify which elements of a list of distance matrices should be kept or dropped before formatting the distance matrices.
#'
#'@export
identifyObsxPredsABMatrices <- function(
  dist.matrices
){
  
  # Get names
  
  dist.names <- names(dist.matrices)
  
  # Find names corresponding to left-and-right obsxpreds matrices
  
  ind1 <- grep(".a", dist.names)
  ind2 <- grep(".b", dist.names)
  inds <- union(ind1, ind2)
  
  # Spit out indices
  
  return(inds)
  
}